//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Runner.rc
//
// This file is auto-generated by tool/icon_build.dart. Do not edit.
//
#define IDI_APP_ICON                    101
#define IDI_APP_ICON_ALT                102
#define IDI_APP_ICON_RENR                103
#define IDI_APP_ICON_GONGZOUCHAO                104
#define IDI_APP_ICON_YURUGONGZOU                105
#define IDI_APP_ICON_ZOUCHAO                106
#define IDI_APP_ICON_ZOUHUAN                107
#define IDI_APP_ICON_ZOUSHEN                108

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        109
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif

